name: ✨ Feature Request
description: Suggest a new feature or enhancement for ClearCrash
title: "[Feature]: "
labels: [ "enhancement", "needs-triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see added.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like ClearCrash to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how this feature would work with code examples
      placeholder: |
        // Example:
        ClearCrash.configure {
            customErrorType<MyException> { ... }
        }
      render: kotlin
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I considered using...
    validations:
      required: false

  - type: dropdown
    id: error-type
    attributes:
      label: Is this for a new error type?
      description: Are you requesting support for a new exception type?
      options:
        - "Yes - New error type"
        - "No - General enhancement"
    validations:
      required: true

  - type: input
    id: error-class
    attributes:
      label: Error Class (if applicable)
      description: If requesting a new error type, which exception class?
      placeholder: "androidx.fragment.app.FragmentException"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: This would be useful because...
    validations:
      required: false
